# Generated by Django 4.2.3 on 2023-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=20)),
                ('order_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
